version: '5'

services:
  dots_www:
    tty: true
    container_name: dots_www
    hostname: dots_www
    build: ./
    environment:
     - VIRTUAL_HOST=www.dots.volt.com
     - VIRTUAL_PORT=8080
     - VIRTUAL_PORT_SSL=8443
     - HTTPS_METHOD=noredirect
    extra_hosts:
      - "api.dots.volt.com:172.16.0.1"
    user: "$UID:0"
    working_dir: /var/www/html/public
    volumes:
     - ./www/distant:/var/www/html/public:rw
     - ~/.ssh:/tmp/.ssh
     - ~/.ssh:/root/.ssh
     - ./files/etc/nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf
     - ./files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
     - dots_proxy_net
networks:
  dots_proxy_net:
    external: true

